-- AUTO-GENERATED by scripts/dump-schema.mjs — do not edit by hand.
-- Dumped from live DB via Supabase Management API (pg catalogs).
-- Regenerate with `pnpm dump-schema`.
--
-- Represents the CURRENT production state of the public schema. Run
-- against a fresh DB to reproduce the live schema. Does NOT include
-- auth / storage (Supabase-managed) nor seed data.

-- ============================================================
-- Extensions
-- ============================================================

create extension if not exists "pg_graphql";
create extension if not exists "pg_stat_statements";
create extension if not exists "pgcrypto";
create extension if not exists "supabase_vault";
create extension if not exists "uuid-ossp";

-- ============================================================
-- Tables
-- ============================================================

create table public.assignment_submissions (
  id uuid not null default gen_random_uuid(),
  assignment_id uuid not null,
  submitted_text text not null default ''::text,
  submitted_at timestamp with time zone not null default now(),
  teacher_feedback text,
  score text,
  graded_at timestamp with time zone,
  primary key (id)
);

create table public.assignments (
  id uuid not null default gen_random_uuid(),
  teacher_id uuid not null,
  student_id uuid not null,
  title text not null,
  instructions text not null default ''::text,
  due_at timestamp with time zone,
  status text not null default 'open'::text,
  created_at timestamp with time zone not null default now(),
  primary key (id)
);

create table public.availability_slots (
  id uuid not null default uuid_generate_v4(),
  teacher_id uuid not null,
  day_of_week integer not null,
  start_time time without time zone not null,
  end_time time without time zone not null,
  is_active boolean default true,
  primary key (id)
);

create table public.bookings (
  id uuid not null default uuid_generate_v4(),
  student_id uuid not null,
  teacher_id uuid,
  scheduled_at timestamp with time zone not null,
  duration_minutes integer not null default 60,
  status text not null default 'pending'::text,
  video_room_url text,
  video_room_name text,
  notes jsonb,
  student_notes text,
  created_at timestamp with time zone not null default now(),
  type text not null default 'class'::text,
  meeting_notes text,
  conductor_profile_id uuid,
  primary key (id)
);

create table public.payments (
  id uuid not null default uuid_generate_v4(),
  booking_id uuid,
  student_id uuid not null,
  teacher_id uuid not null,
  amount_usd numeric(10,2) not null,
  platform_fee_usd numeric(10,2) not null,
  teacher_payout_usd numeric(10,2) not null,
  stripe_payment_intent_id text,
  stripe_transfer_id text,
  status text not null default 'pending'::text,
  created_at timestamp with time zone not null default now(),
  primary key (id)
);

create table public.plans (
  id uuid not null default uuid_generate_v4(),
  name text not null,
  name_es text not null,
  classes_per_month integer not null,
  price_usd numeric(10,2) not null,
  stripe_price_id text,
  description text,
  description_es text,
  is_popular boolean default false,
  is_active boolean default true,
  created_at timestamp with time zone not null default now(),
  plan_key text,
  primary key (id)
);

create table public.profiles (
  id uuid not null,
  email text not null,
  full_name text not null,
  avatar_url text,
  role text not null default 'student'::text,
  timezone text not null default 'America/Guatemala'::text,
  preferred_language text not null default 'es'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  phone text,
  preferred_currency text default 'USD'::text,
  notification_preferences jsonb default jsonb_build_object('email', true, 'sms', false, 'whatsapp', false, 'before24h', true, 'before1h', true),
  primary key (id)
);

create table public.sessions (
  id uuid not null default uuid_generate_v4(),
  booking_id uuid not null,
  started_at timestamp with time zone,
  ended_at timestamp with time zone,
  recording_url text,
  teacher_notes text,
  student_rating integer,
  student_review text,
  created_at timestamp with time zone not null default now(),
  notes text,
  primary key (id)
);

create table public.students (
  id uuid not null default uuid_generate_v4(),
  profile_id uuid not null,
  level text,
  classes_remaining integer default 0,
  stripe_customer_id text,
  placement_test_done boolean default false,
  created_at timestamp with time zone not null default now(),
  learning_goal text,
  work_description text,
  learning_style text,
  age_range text,
  intake_done boolean not null default false,
  survey_answers jsonb,
  current_plan text,
  placement_scheduled boolean default false,
  admin_notes text,
  primary_teacher_id uuid,
  primary key (id)
);

create table public.subscriptions (
  id uuid not null default uuid_generate_v4(),
  student_id uuid not null,
  plan_id uuid not null,
  stripe_subscription_id text,
  status text not null default 'trialing'::text,
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  primary key (id)
);

create table public.teachers (
  id uuid not null default uuid_generate_v4(),
  profile_id uuid not null,
  bio text,
  specializations text[] default '{}'::text[],
  certifications text[] default '{}'::text[],
  hourly_rate numeric(10,2) not null default 0,
  rating numeric(3,2),
  total_sessions integer default 0,
  stripe_account_id text,
  is_active boolean default true,
  created_at timestamp with time zone not null default now(),
  admin_notes text,
  primary key (id)
);

-- ============================================================
-- Foreign Keys
-- ============================================================

alter table public.assignment_submissions add constraint assignment_submissions_assignment_id_fkey foreign key (assignment_id) references public.assignments (id) on delete cascade;
alter table public.assignments add constraint assignments_student_id_fkey foreign key (student_id) references public.students (id) on delete cascade;
alter table public.assignments add constraint assignments_teacher_id_fkey foreign key (teacher_id) references public.teachers (id) on delete cascade;
alter table public.availability_slots add constraint availability_slots_teacher_id_fkey foreign key (teacher_id) references public.teachers (id) on delete cascade;
alter table public.bookings add constraint bookings_conductor_profile_id_fkey foreign key (conductor_profile_id) references public.profiles (id);
alter table public.bookings add constraint bookings_student_id_fkey foreign key (student_id) references public.students (id) on delete cascade;
alter table public.bookings add constraint bookings_teacher_id_fkey foreign key (teacher_id) references public.teachers (id) on delete cascade;
alter table public.payments add constraint payments_booking_id_fkey foreign key (booking_id) references public.bookings (id);
alter table public.payments add constraint payments_student_id_fkey foreign key (student_id) references public.students (id);
alter table public.payments add constraint payments_teacher_id_fkey foreign key (teacher_id) references public.teachers (id);
alter table public.profiles add constraint profiles_id_fkey foreign key (id) references auth.users (id) on delete cascade;
alter table public.sessions add constraint sessions_booking_id_fkey foreign key (booking_id) references public.bookings (id) on delete cascade;
alter table public.students add constraint students_primary_teacher_id_fkey foreign key (primary_teacher_id) references public.teachers (id);
alter table public.students add constraint students_profile_id_fkey foreign key (profile_id) references public.profiles (id) on delete cascade;
alter table public.subscriptions add constraint subscriptions_plan_id_fkey foreign key (plan_id) references public.plans (id);
alter table public.subscriptions add constraint subscriptions_student_id_fkey foreign key (student_id) references public.students (id) on delete cascade;
alter table public.teachers add constraint teachers_profile_id_fkey foreign key (profile_id) references public.profiles (id) on delete cascade;

-- ============================================================
-- Check Constraints
-- ============================================================

alter table public.assignment_submissions add constraint assignment_submissions_score_check CHECK (((score IS NULL) OR (score = ANY (ARRAY['A1'::text, 'A2'::text, 'B1'::text, 'B2'::text, 'C1'::text, 'C2'::text, 'needs_work'::text, 'good'::text, 'excellent'::text]))));
alter table public.assignments add constraint assignments_status_check CHECK ((status = ANY (ARRAY['open'::text, 'cancelled'::text])));
alter table public.availability_slots add constraint availability_slots_day_of_week_check CHECK (((day_of_week >= 0) AND (day_of_week <= 6)));
alter table public.bookings add constraint bookings_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text])));
alter table public.payments add constraint payments_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])));
alter table public.profiles add constraint profiles_preferred_currency_len CHECK (((preferred_currency IS NULL) OR (length(preferred_currency) = 3)));
alter table public.profiles add constraint profiles_preferred_language_check CHECK ((preferred_language = ANY (ARRAY['es'::text, 'en'::text])));
alter table public.profiles add constraint profiles_role_check CHECK ((role = ANY (ARRAY['student'::text, 'teacher'::text, 'admin'::text])));
alter table public.sessions add constraint sessions_student_rating_check CHECK (((student_rating >= 1) AND (student_rating <= 5)));
alter table public.students add constraint students_age_range_check CHECK ((age_range = ANY (ARRAY['under_18'::text, '18_25'::text, '26_40'::text, '40_plus'::text])));
alter table public.students add constraint students_learning_style_check CHECK ((learning_style = ANY (ARRAY['visual'::text, 'auditory'::text, 'reading'::text, 'mixed'::text])));
alter table public.students add constraint students_level_check CHECK ((level = ANY (ARRAY['A1'::text, 'A2'::text, 'B1'::text, 'B2'::text, 'C1'::text, 'C2'::text])));
alter table public.subscriptions add constraint subscriptions_status_check CHECK ((status = ANY (ARRAY['active'::text, 'cancelled'::text, 'past_due'::text, 'trialing'::text])));

-- ============================================================
-- Unique Constraints
-- ============================================================

alter table public.assignment_submissions add constraint assignment_submissions_assignment_id_key UNIQUE (assignment_id);
alter table public.payments add constraint payments_stripe_payment_intent_id_key UNIQUE (stripe_payment_intent_id);
alter table public.students add constraint students_profile_id_key UNIQUE (profile_id);
alter table public.subscriptions add constraint subscriptions_stripe_subscription_id_key UNIQUE (stripe_subscription_id);
alter table public.teachers add constraint teachers_profile_id_key UNIQUE (profile_id);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX idx_submissions_assignment ON public.assignment_submissions USING btree (assignment_id);
CREATE INDEX idx_assignments_student ON public.assignments USING btree (student_id, created_at DESC);
CREATE INDEX idx_assignments_teacher ON public.assignments USING btree (teacher_id, created_at DESC);
CREATE INDEX idx_availability_teacher ON public.availability_slots USING btree (teacher_id);
CREATE UNIQUE INDEX bookings_student_time_unique ON public.bookings USING btree (student_id, scheduled_at) WHERE (status <> 'cancelled'::text);
CREATE INDEX idx_bookings_pending_class_assignment ON public.bookings USING btree (scheduled_at) WHERE ((type = 'class'::text) AND (teacher_id IS NULL) AND (status <> 'cancelled'::text));
CREATE INDEX idx_bookings_pending_placement_assignment ON public.bookings USING btree (scheduled_at) WHERE ((type = 'placement_test'::text) AND (conductor_profile_id IS NULL) AND (status <> 'cancelled'::text));
CREATE INDEX idx_bookings_scheduled_at ON public.bookings USING btree (scheduled_at);
CREATE INDEX idx_bookings_student ON public.bookings USING btree (student_id);
CREATE INDEX idx_bookings_teacher ON public.bookings USING btree (teacher_id);
CREATE INDEX idx_payments_student ON public.payments USING btree (student_id);
CREATE INDEX idx_payments_teacher ON public.payments USING btree (teacher_id);
CREATE UNIQUE INDEX plans_plan_key_key ON public.plans USING btree (plan_key);

-- ============================================================
-- Row-Level Security
-- ============================================================

alter table public.assignment_submissions enable row level security;
alter table public.assignments enable row level security;
alter table public.availability_slots enable row level security;
alter table public.bookings enable row level security;
alter table public.payments enable row level security;
alter table public.plans enable row level security;
alter table public.profiles enable row level security;
alter table public.sessions enable row level security;
alter table public.students enable row level security;
alter table public.subscriptions enable row level security;
alter table public.teachers enable row level security;

-- ============================================================
-- Policies
-- ============================================================

create policy "admin reads submissions" on public.assignment_submissions for select using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));
create policy "student reads own submissions" on public.assignment_submissions for select using ((assignment_id IN ( SELECT assignments.id
   FROM assignments
  WHERE (assignments.student_id IN ( SELECT students.id
           FROM students
          WHERE (students.profile_id = auth.uid()))))));
create policy "teacher reads own submissions" on public.assignment_submissions for select using ((assignment_id IN ( SELECT assignments.id
   FROM assignments
  WHERE (assignments.teacher_id IN ( SELECT teachers.id
           FROM teachers
          WHERE (teachers.profile_id = auth.uid()))))));
create policy "admin reads assignments" on public.assignments for select using ((EXISTS ( SELECT 1
   FROM profiles
  WHERE ((profiles.id = auth.uid()) AND (profiles.role = 'admin'::text)))));
create policy "student reads own assignments" on public.assignments for select using ((student_id IN ( SELECT students.id
   FROM students
  WHERE (students.profile_id = auth.uid()))));
create policy "teacher reads own assignments" on public.assignments for select using ((teacher_id IN ( SELECT teachers.id
   FROM teachers
  WHERE (teachers.profile_id = auth.uid()))));
create policy "Availability slots are publicly visible" on public.availability_slots for select using ((is_active = true));
create policy "Teachers manage own availability" on public.availability_slots for all using ((auth.uid() = ( SELECT teachers.profile_id
   FROM teachers
  WHERE (teachers.id = availability_slots.teacher_id))));
create policy "Students can create bookings" on public.bookings for insert to authenticated with check ((student_id = auth_student_id()));
create policy "Students see own bookings" on public.bookings for select to authenticated using ((student_id = auth_student_id()));
create policy "Teachers can update booking status" on public.bookings for update using ((auth.uid() = ( SELECT teachers.profile_id
   FROM teachers
  WHERE (teachers.id = bookings.teacher_id))));
create policy "Teachers see own bookings" on public.bookings for select using ((auth.uid() = ( SELECT teachers.profile_id
   FROM teachers
  WHERE (teachers.id = bookings.teacher_id))));
create policy "Students see own payments" on public.payments for select using ((auth.uid() = ( SELECT students.profile_id
   FROM students
  WHERE (students.id = payments.student_id))));
create policy "Teachers see own payments" on public.payments for select using ((auth.uid() = ( SELECT teachers.profile_id
   FROM teachers
  WHERE (teachers.id = payments.teacher_id))));
create policy "Plans are publicly visible" on public.plans for select using ((is_active = true));
create policy "Students can read teacher profiles" on public.profiles for select using ((EXISTS ( SELECT 1
   FROM ((teachers t
     JOIN bookings b ON ((b.teacher_id = t.id)))
     JOIN students s ON ((s.id = b.student_id)))
  WHERE ((t.profile_id = profiles.id) AND (s.profile_id = auth.uid())))));
create policy "Users can update own profile" on public.profiles for update using ((auth.uid() = id));
create policy "Users can view own profile" on public.profiles for select using ((auth.uid() = id));
create policy "Session participants can view" on public.sessions for select using ((auth.uid() IN ( SELECT p.profile_id
   FROM (students p
     JOIN bookings b ON ((b.student_id = p.id)))
  WHERE (b.id = sessions.booking_id)
UNION
 SELECT t.profile_id
   FROM (teachers t
     JOIN bookings b ON ((b.teacher_id = t.id)))
  WHERE (b.id = sessions.booking_id))));
create policy "Students can read own sessions" on public.sessions for select using ((EXISTS ( SELECT 1
   FROM (bookings b
     JOIN students s ON ((s.id = b.student_id)))
  WHERE ((b.id = sessions.booking_id) AND (s.profile_id = auth.uid())))));
create policy "Teachers can insert sessions" on public.sessions for insert with check ((EXISTS ( SELECT 1
   FROM (bookings b
     JOIN teachers t ON ((t.id = b.teacher_id)))
  WHERE ((b.id = sessions.booking_id) AND (t.profile_id = auth.uid())))));
create policy "Teachers can update sessions" on public.sessions for update using ((EXISTS ( SELECT 1
   FROM (bookings b
     JOIN teachers t ON ((t.id = b.teacher_id)))
  WHERE ((b.id = sessions.booking_id) AND (t.profile_id = auth.uid())))));
create policy "Students can insert own record" on public.students for insert to authenticated with check ((auth.uid() = profile_id));
create policy "Students can update own record" on public.students for update using ((auth.uid() = profile_id));
create policy "Students can view own record" on public.students for select using ((auth.uid() = profile_id));
create policy "Teachers can read student intake" on public.students for select using ((auth.uid() IN ( SELECT t.profile_id
   FROM (teachers t
     JOIN bookings b ON ((b.teacher_id = t.id)))
  WHERE (b.student_id = students.id))));
create policy "Students can view own subscriptions" on public.subscriptions for select using ((auth.uid() = ( SELECT students.profile_id
   FROM students
  WHERE (students.id = subscriptions.student_id))));
create policy "Teachers are publicly visible" on public.teachers for select using ((is_active = true));
create policy "Teachers can insert their own record" on public.teachers for insert with check ((profile_id = auth.uid()));
create policy "Teachers can update own record" on public.teachers for update using ((auth.uid() = profile_id));
create policy "Teachers can view own record" on public.teachers for select using ((auth.uid() = profile_id));

-- ============================================================
-- Functions
-- ============================================================

CREATE OR REPLACE FUNCTION public.add_classes(p_student_id uuid, p_count integer)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE students
  SET classes_remaining = classes_remaining + p_count
  WHERE id = p_student_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.auth_student_id()
 RETURNS uuid
 LANGUAGE sql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$ SELECT id FROM students WHERE profile_id = auth.uid() LIMIT 1; $function$
;

CREATE OR REPLACE FUNCTION public.decrement_classes(p_student_id uuid)
 RETURNS boolean
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$ DECLARE rows_updated int; BEGIN UPDATE students SET classes_remaining = classes_remaining - 1 WHERE id = p_student_id AND classes_remaining > 0; GET DIAGNOSTICS rows_updated = ROW_COUNT; RETURN rows_updated > 0; END; $function$
;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
begin
  insert into public.profiles (id, email, full_name, role)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'student')
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.increment_classes(p_student_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  UPDATE students
  SET classes_remaining = classes_remaining + 1
  WHERE id = p_student_id;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
 RETURNS event_trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'pg_catalog'
AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$
;

-- ============================================================
-- Triggers
-- ============================================================

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION handle_new_user();

-- ============================================================
-- Event Triggers
-- ============================================================

create event trigger ensure_rls on ddl_command_end when tag in ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO') execute function public.rls_auto_enable();
