// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate with `pnpm gen-types` after any migration that alters the
// public schema. Source: Supabase Management API /types/typescript.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      assignment_submissions: {
        Row: {
          assignment_id: string
          graded_at: string | null
          id: string
          score: string | null
          submitted_at: string
          submitted_text: string
          teacher_feedback: string | null
        }
        Insert: {
          assignment_id: string
          graded_at?: string | null
          id?: string
          score?: string | null
          submitted_at?: string
          submitted_text?: string
          teacher_feedback?: string | null
        }
        Update: {
          assignment_id?: string
          graded_at?: string | null
          id?: string
          score?: string | null
          submitted_at?: string
          submitted_text?: string
          teacher_feedback?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "assignment_submissions_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: true
            referencedRelation: "assignments"
            referencedColumns: ["id"]
          },
        ]
      }
      assignments: {
        Row: {
          created_at: string
          due_at: string | null
          id: string
          instructions: string
          status: string
          student_id: string
          teacher_id: string
          title: string
        }
        Insert: {
          created_at?: string
          due_at?: string | null
          id?: string
          instructions?: string
          status?: string
          student_id: string
          teacher_id: string
          title: string
        }
        Update: {
          created_at?: string
          due_at?: string | null
          id?: string
          instructions?: string
          status?: string
          student_id?: string
          teacher_id?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "assignments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignments_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
        ]
      }
      availability_slots: {
        Row: {
          day_of_week: number
          end_time: string
          id: string
          is_active: boolean | null
          start_time: string
          teacher_id: string
        }
        Insert: {
          day_of_week: number
          end_time: string
          id?: string
          is_active?: boolean | null
          start_time: string
          teacher_id: string
        }
        Update: {
          day_of_week?: number
          end_time?: string
          id?: string
          is_active?: boolean | null
          start_time?: string
          teacher_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "availability_slots_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
        ]
      }
      bookings: {
        Row: {
          conductor_profile_id: string | null
          created_at: string
          duration_minutes: number
          id: string
          meeting_notes: string | null
          notes: Json | null
          scheduled_at: string
          status: string
          student_id: string
          student_notes: string | null
          teacher_id: string | null
          type: string
          video_room_name: string | null
          video_room_url: string | null
        }
        Insert: {
          conductor_profile_id?: string | null
          created_at?: string
          duration_minutes?: number
          id?: string
          meeting_notes?: string | null
          notes?: Json | null
          scheduled_at: string
          status?: string
          student_id: string
          student_notes?: string | null
          teacher_id?: string | null
          type?: string
          video_room_name?: string | null
          video_room_url?: string | null
        }
        Update: {
          conductor_profile_id?: string | null
          created_at?: string
          duration_minutes?: number
          id?: string
          meeting_notes?: string | null
          notes?: Json | null
          scheduled_at?: string
          status?: string
          student_id?: string
          student_notes?: string | null
          teacher_id?: string | null
          type?: string
          video_room_name?: string | null
          video_room_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "bookings_conductor_profile_id_fkey"
            columns: ["conductor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "bookings_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount_usd: number
          booking_id: string | null
          created_at: string
          id: string
          platform_fee_usd: number
          status: string
          stripe_payment_intent_id: string | null
          stripe_transfer_id: string | null
          student_id: string
          teacher_id: string
          teacher_payout_usd: number
        }
        Insert: {
          amount_usd: number
          booking_id?: string | null
          created_at?: string
          id?: string
          platform_fee_usd: number
          status?: string
          stripe_payment_intent_id?: string | null
          stripe_transfer_id?: string | null
          student_id: string
          teacher_id: string
          teacher_payout_usd: number
        }
        Update: {
          amount_usd?: number
          booking_id?: string | null
          created_at?: string
          id?: string
          platform_fee_usd?: number
          status?: string
          stripe_payment_intent_id?: string | null
          stripe_transfer_id?: string | null
          student_id?: string
          teacher_id?: string
          teacher_payout_usd?: number
        }
        Relationships: [
          {
            foreignKeyName: "payments_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
        ]
      }
      plans: {
        Row: {
          classes_per_month: number
          created_at: string
          description: string | null
          description_es: string | null
          id: string
          is_active: boolean | null
          is_popular: boolean | null
          name: string
          name_es: string
          plan_key: string | null
          price_usd: number
          stripe_price_id: string | null
        }
        Insert: {
          classes_per_month: number
          created_at?: string
          description?: string | null
          description_es?: string | null
          id?: string
          is_active?: boolean | null
          is_popular?: boolean | null
          name: string
          name_es: string
          plan_key?: string | null
          price_usd: number
          stripe_price_id?: string | null
        }
        Update: {
          classes_per_month?: number
          created_at?: string
          description?: string | null
          description_es?: string | null
          id?: string
          is_active?: boolean | null
          is_popular?: boolean | null
          name?: string
          name_es?: string
          plan_key?: string | null
          price_usd?: number
          stripe_price_id?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          email: string
          full_name: string
          id: string
          notification_preferences: Json | null
          phone: string | null
          preferred_currency: string | null
          preferred_language: string
          role: string
          timezone: string
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          email: string
          full_name: string
          id: string
          notification_preferences?: Json | null
          phone?: string | null
          preferred_currency?: string | null
          preferred_language?: string
          role?: string
          timezone?: string
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          email?: string
          full_name?: string
          id?: string
          notification_preferences?: Json | null
          phone?: string | null
          preferred_currency?: string | null
          preferred_language?: string
          role?: string
          timezone?: string
          updated_at?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          booking_id: string
          created_at: string
          ended_at: string | null
          id: string
          notes: string | null
          recording_url: string | null
          started_at: string | null
          student_rating: number | null
          student_review: string | null
          teacher_notes: string | null
        }
        Insert: {
          booking_id: string
          created_at?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          recording_url?: string | null
          started_at?: string | null
          student_rating?: number | null
          student_review?: string | null
          teacher_notes?: string | null
        }
        Update: {
          booking_id?: string
          created_at?: string
          ended_at?: string | null
          id?: string
          notes?: string | null
          recording_url?: string | null
          started_at?: string | null
          student_rating?: number | null
          student_review?: string | null
          teacher_notes?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "sessions_booking_id_fkey"
            columns: ["booking_id"]
            isOneToOne: false
            referencedRelation: "bookings"
            referencedColumns: ["id"]
          },
        ]
      }
      students: {
        Row: {
          admin_notes: string | null
          age_range: string | null
          classes_remaining: number | null
          created_at: string
          current_plan: string | null
          id: string
          intake_done: boolean
          learning_goal: string | null
          learning_style: string | null
          level: string | null
          placement_scheduled: boolean | null
          placement_test_done: boolean | null
          primary_teacher_id: string | null
          profile_id: string
          stripe_customer_id: string | null
          survey_answers: Json | null
          work_description: string | null
        }
        Insert: {
          admin_notes?: string | null
          age_range?: string | null
          classes_remaining?: number | null
          created_at?: string
          current_plan?: string | null
          id?: string
          intake_done?: boolean
          learning_goal?: string | null
          learning_style?: string | null
          level?: string | null
          placement_scheduled?: boolean | null
          placement_test_done?: boolean | null
          primary_teacher_id?: string | null
          profile_id: string
          stripe_customer_id?: string | null
          survey_answers?: Json | null
          work_description?: string | null
        }
        Update: {
          admin_notes?: string | null
          age_range?: string | null
          classes_remaining?: number | null
          created_at?: string
          current_plan?: string | null
          id?: string
          intake_done?: boolean
          learning_goal?: string | null
          learning_style?: string | null
          level?: string | null
          placement_scheduled?: boolean | null
          placement_test_done?: boolean | null
          primary_teacher_id?: string | null
          profile_id?: string
          stripe_customer_id?: string | null
          survey_answers?: Json | null
          work_description?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "students_primary_teacher_id_fkey"
            columns: ["primary_teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "students_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      subscriptions: {
        Row: {
          created_at: string
          current_period_end: string | null
          current_period_start: string | null
          id: string
          plan_id: string
          status: string
          stripe_subscription_id: string | null
          student_id: string
        }
        Insert: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          plan_id: string
          status?: string
          stripe_subscription_id?: string | null
          student_id: string
        }
        Update: {
          created_at?: string
          current_period_end?: string | null
          current_period_start?: string | null
          id?: string
          plan_id?: string
          status?: string
          stripe_subscription_id?: string | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "subscriptions_plan_id_fkey"
            columns: ["plan_id"]
            isOneToOne: false
            referencedRelation: "plans"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subscriptions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      teachers: {
        Row: {
          admin_notes: string | null
          bio: string | null
          certifications: string[] | null
          created_at: string
          hourly_rate: number
          id: string
          is_active: boolean | null
          profile_id: string
          rating: number | null
          specializations: string[] | null
          stripe_account_id: string | null
          total_sessions: number | null
        }
        Insert: {
          admin_notes?: string | null
          bio?: string | null
          certifications?: string[] | null
          created_at?: string
          hourly_rate?: number
          id?: string
          is_active?: boolean | null
          profile_id: string
          rating?: number | null
          specializations?: string[] | null
          stripe_account_id?: string | null
          total_sessions?: number | null
        }
        Update: {
          admin_notes?: string | null
          bio?: string | null
          certifications?: string[] | null
          created_at?: string
          hourly_rate?: number
          id?: string
          is_active?: boolean | null
          profile_id?: string
          rating?: number | null
          specializations?: string[] | null
          stripe_account_id?: string | null
          total_sessions?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "teachers_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_classes: {
        Args: { p_count: number; p_student_id: string }
        Returns: undefined
      }
      auth_student_id: { Args: never; Returns: string }
      decrement_classes: { Args: { p_student_id: string }; Returns: boolean }
      increment_classes: { Args: { p_student_id: string }; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
