/**
 * Regenerate `src/types/supabase.ts` from the live database schema via the
 * Supabase Management API. We deliberately do NOT shell out to the `supabase`
 * CLI — it's not installed in this dev / CI environment and the Management
 * API endpoint below returns the exact same TypeScript emit.
 *
 *   GET https://api.supabase.com/v1/projects/<ref>/types/typescript?included_schemas=public
 *   → { "types": "... .d.ts source ..." }
 *
 * Run after any migration that adds / renames / drops a column, table, enum,
 * or function. CI should also run this and fail if the committed types file
 * is stale (see `.github/workflows/*.yml`).
 *
 * Usage:
 *   pnpm gen-types
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const projectRoot = resolve(__dirname, '..')

// Env loader — mirrors the pattern in tests/fixtures/bookingFixture.ts and
// scripts/reset-test-passwords.js. Reads .env.local if present but never
// overrides values already exported into process.env.
;(function loadEnvLocal() {
  const envPath = join(projectRoot, '.env.local')
  try {
    const raw = readFileSync(envPath, 'utf8')
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/i)
      if (!m) continue
      const [, k, vRaw] = m
      if (process.env[k]) continue
      process.env[k] = vRaw.replace(/^['"]|['"]$/g, '')
    }
  } catch {
    // .env.local is optional in CI where vars come from the runner env.
  }
})()

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL
const accessToken = process.env.SUPABASE_ACCESS_TOKEN

if (!supabaseUrl || !accessToken) {
  console.error(
    'gen-types: missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_ACCESS_TOKEN.\n' +
    'Set both in .env.local (SUPABASE_ACCESS_TOKEN is a personal access token\n' +
    'from https://supabase.com/dashboard/account/tokens).',
  )
  process.exit(1)
}

const refMatch = supabaseUrl.match(/https?:\/\/([a-z0-9]+)\.supabase\.co/i)
const ref = refMatch?.[1]
if (!ref) {
  console.error(`gen-types: could not parse project ref from ${supabaseUrl}`)
  process.exit(1)
}

const endpoint = `https://api.supabase.com/v1/projects/${ref}/types/typescript?included_schemas=public`

console.log(`gen-types: fetching from ${endpoint}`)

const res = await fetch(endpoint, {
  headers: { Authorization: `Bearer ${accessToken}` },
})

if (!res.ok) {
  console.error(`gen-types: HTTP ${res.status} ${res.statusText}`)
  console.error(await res.text())
  process.exit(1)
}

const body = await res.json()
const types = body?.types
if (typeof types !== 'string' || types.length < 100) {
  console.error('gen-types: response did not include a `types` string:')
  console.error(JSON.stringify(body).slice(0, 500))
  process.exit(1)
}

const outDir = join(projectRoot, 'src', 'types')
mkdirSync(outDir, { recursive: true })
const outPath = join(outDir, 'supabase.ts')

const header =
  '// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.\n' +
  '// Regenerate with `pnpm gen-types` after any migration that alters the\n' +
  '// public schema. Source: Supabase Management API /types/typescript.\n\n'

writeFileSync(outPath, header + types, 'utf8')
console.log(`gen-types: wrote ${outPath} (${types.length} chars)`)
